APPWRITE_PROJECT_ID=674b9cee000c87bb143e
APPWRITE_ENDPOINT=https://fra.cloud.appwrite.io/v1
APPWRITE_ENDPOINT_FUNCTION=https://6a03eddc0001bc9adf0f.fra.appwrite.run
APPWRITE_GATEWAY_FUNCTION_ID=69ec9e410022fa3fa3f1
APPWRITE_DATABASE_ID=69eca97100090be1e45e

# Collection IDs (Table IDs)
APPWRITE_COL_USERS=users
APPWRITE_COL_TRANSACTIONS=transactions
APPWRITE_COL_GOALS=goals
APPWRITE_COL_DEBTS=debts
APPWRITE_COL_FAMILIES=families
APPWRITE_COL_MESSAGES=messages
APPWRITE_COL_INCOMES=incomes
APPWRITE_COL_NOTIFICATIONS=notifications
APPWRITE_COL_LIKES=likes
APPWRITE_COL_COMMENTS=comments
GEMINI_API_KEY=AIzaSyBFuJN04vrCld77VZjf-4QX_zuzTSpJ7cE
#APP_SIGNATURE_HASH=1F:3B:9E:EE:05:D2:CC:99:4C:CE:BD:26:40:01:D9:49:E9:CB:8D:68:E1:4A:1C:B0:5B:AF:F5:4D:03:8D:4E:0E
APP_SIGNATURE_HASH=2B:A2:6A:93:F7:C4:A7:7B:7A:B7:7A:B7:38:77:A7:85:99:BB:74:6D:BC:ED:18:24:3D:9C:50:4F:DE:F7:3B:55