APPWRITE_PROJECT_ID=674b9cee000c87bb143e
APPWRITE_ENDPOINT=https://fra.cloud.appwrite.io/v1
APPWRITE_ENDPOINT_FUNCTION=https://6a03eddc0001bc9adf0f.fra.appwrite.run
APPWRITE_GATEWAY_FUNCTION_ID=69ec9e410022fa3fa3f1
APPWRITE_DATABASE_ID=69eca97100090be1e45e

# Collection IDs (Table IDs)
APPWRITE_COL_USERS=users
APPWRITE_COL_TRANSACTIONS=transactions
APPWRITE_COL_GOALS=goals
APPWRITE_COL_DEBTS=debts
APPWRITE_COL_FAMILIES=families
APPWRITE_COL_MESSAGES=messages
APPWRITE_COL_INCOMES=incomes
